### ISSUE TITLE
sample mp3 files Artist & Title field missing, missing reference in "?" Dialog

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#103]
If I open the files (on my Mac M1 running Parallels with an ARM Windows 11...) I can play the sample mp3s but Artist and Title does not get loaded. Either we have to adjust the id-tags or have a look why it doesnt load them. 

In the "?" dialog, the mo3 credits should be referenced.

**Comment by philippReist** [comment]
Yes, the artist and title should be added - need to double check loading, too.

We do not need to credit in the ? - I bought the rights for the songs for use without attribution.

**Comment by tiemes** [comment]
I think the files don't have the tags filled out. 
Alright, then crediting is not necessary..

**Comment by philippReist** [comment]
Fixed this - the sample files have the artist and title included now. And I added precompiled beat data to speed it up further.
