### ISSUE TITLE
Asset File Name

### ISSUE THREAD

**Issue by ray-hrst** [philippReist/DanceBotsEditor#58]
In the v1 release, the Windows binary is named `DanceBotsEditor-v1.0.0.zip`. It might not be obvious to some that this is Windows binary considering the others are called:
- dancebots-editor-darwin-v1.0.0.dmg
- dancebots-editor-ubuntu-v1.0.0.tar.gz

You might want to re-label it, for example:
- dancebots-editor-win32-v1.0.0.zip or
- dancebots-editor-win64-v1.0.0.zip 

Also, maybe the repository should be renamed from `dancebots_gui` to `dancebots_editor`? Just to be consistent.

**Comment by philippReist** [comment]
Good suggestions! I updated the repo name and will update the win release as well.
