### ISSUE TITLE
MacOS Version Compatibility

### ISSUE THREAD

**Issue by philippReist** [philippReist/DanceBotsEditor#59]
Just to keep tabs on this. Could not run the release on my Mac book either. Would be good to not be too restrictive about the version of MacOS that the GUI can run on.

**Comment by philippReist** [comment]
I created a manual release on my Mojave machine for now. But it might be that older versions will not work with this either.

**Comment by ray-hrst** [comment]
I'll take a look. The runners on github are using Xcode 11.3 by default (https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md). According [this](https://doc.qt.io/qt-5/macos.html) it should be possible to target macOS 10.13 and above.
