### ISSUE TITLE
mp3 player with swapped r/l audio channels

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#62]
our new (extremely expensive aliexpress ;-)) mp3 players have R/L audio swapped. To use them, we'd need to be able to swap channels in the software as well. maybe, we could include a 'options' dialog next to 'clear' or hide it behind the '?' dialog. 
I hope, swapping channels wouldnt be a huge deal?

**Comment by philippReist** [comment]
Hmm, this happened to us as well back in the day and I ended up soldering to fix the mp3 output.

I'll have a look this weekend. Should not be hard to add, I agree.

**Comment by philippReist** [comment]
Ok, I think this should work: https://github.com/philippReist/DanceBotsEditor/tree/feature-swapAudioChannels

Can you test (on Mac in particular as well?).

Note that on a fresh install, I used 5.12.9 LTS and that worked.

**Comment by tiemes** [comment]
Tanks a lot! We'll test.
I only have win and linux but I could probably use a PHZH Mac.
@robinhanhart do you have Mac or could verify it on your system?

**Comment by tiemes** [comment]
<img width="666" alt="db1" src="https://user-images.githubusercontent.com/12649825/98555077-c54a6c00-22a1-11eb-8b9c-eca120b361ec.PNG">

@philippReist I'm not able to build. Any thoughts on that?

**Comment by r-oung** [comment]
FYI. I tested this on Ubuntu and it compiles without error, using:
- cmake 3.16.2
- Qt 5.12.6

@tiemes Can you share the `CMakeOutput.log` and `CMakeError.log` (see the bottom of your screenshot) with us?

@philippReist If you do a PR of this feature branch to the `develop` branch, it should initiate the build-test.

**Comment by philippReist** [comment]
@r-oung: PR and build test is started.

@tiemes: I installed Qt 5.12.9 MSVC 2017 64 bit - so the command for me was `cmake -DCMAKE_PREFIX_PATH=C:\Qt\5.12.9\msvc2017_64\ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" ..`

You can also check what generators are available on your system with cmake -G. Also, my cmake --version output is 3.16.2.

**Comment by tiemes** [comment]
@r-oung here are the files. I installed MSVC2017 first but had (the same issue) so I installed 2015 Version but still the same problem. 
[CMakeError.log](https://github.com/philippReist/DanceBotsEditor/files/5516268/CMakeError.log)
[CMakeOutput.log](https://github.com/philippReist/DanceBotsEditor/files/5516269/CMakeOutput.log)

**Comment by philippReist** [comment]
@tiemes Try working in powershell instead of the mingw shell. Just in case the env. that mingw sets up interferes with the VC cmake setup.

**Comment by tiemes** [comment]
-- Generating done
-- Build files have been written to: C:/DanceBotsEditor/build
thanks @philippReist & @r-oung

**Comment by philippReist** [comment]
Nice!

**Comment by tiemes** [comment]
@philippReist swapping with config.ini worked with my win build. I don't have access to a mac at the time.

**Comment by philippReist** [comment]
@r-oung: So should I merge develop to master for the 1.1.0 release with this?

**Comment by r-oung** [comment]
@philippReist Yes, merge develop to master. Then generate a new release and tag it v1.1.0. The backend should auto-generate the macOS DMG and automatically upload it to the release assets (give it some time). I never got the Windows release to work properly so you'll need to upload that one manually. If it doesn't work, I'll look into it.

**Comment by philippReist** [comment]
Reopened until finished for discussion.

@r-oung - the Ubuntu tarball generated for the release looked too small so I deleted it from the release.

@tiemes - the new release files are here: https://github.com/philippReist/DanceBotsEditor/releases/tag/v1.1.0. Could you please:
- Test the win and mac versions - see also the other comment of @r-oung regarding macos versions.
- Update the dancebots website to point to the new zip/dmg

**Comment by philippReist** [comment]
Closing and adding another one for the new improvements requested by Mint&Pepper
