### ISSUE TITLE
add mp3 sample library

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#65]
just so I dont forget:
it would be nice to have some sample mp3 files in a sample folder so people can start right away without having to know how to get mp3 files.
We have such a sample folder for our laptops. It consists of about 10 30s clips of hitlist songs. Maybe we could include some royalty free music.

**Comment by philippReist** [comment]
Wouldn't it be best to add to the website dancebots.ch? And, in that case, could you just upload your existing collection?

**Comment by tiemes** [comment]
I'd appreciate it, if we had everything one needs in one place. Still, it has to be on the page as well. I'll have to check for copyright infringements with having our library publicly available.

We are just about to finish a new booklet which replaces the cheatsheet and ads a lot if additional information. Also, more Eduguides to certain topics will be developed. As these may also require additional information on websites, it's probably best to wait with the mp3 question until we know more on the other demands.

merry x-mas to you by the way :)

**Comment by philippReist** [comment]
@tiemes please point me to an opensource music file that you would like to distribute with 1.2.0.

**Comment by tiemes** [comment]
@philippReist I finally managed to get two files we can freely distribute. Up to you if we use both or just one
Please add credits to the "?" tab: 
**Music: Singularity & Just Now by Daniel Young https://danielyoung
[MusicByDanielYoung.zip](https://github.com/philippReist/DanceBotsEditor/files/7511156/MusicByDanielYoung.zip)
.ch**

**Comment by philippReist** [comment]
@tiemes Thanks for looking! Unfortunately, these two files get terrible beat detection. But I bought two other songs that we can now ship without any credits. I added them to the repo.
