### ISSUE TITLE
Audio Channel Swap Improvements

### ISSUE THREAD

**Issue by philippReist** [philippReist/DanceBotsEditor#69]
M&P requests a GUI option to swap audio channels. In addition, it would be valuable to detect swapped channels in a dancefile. Therefore I suggest the following tasks:

1. Add a GUI element that allows the user to swap audio channels. In charge: @robinhanhart 
2. Hook up the GUI element to the backend. In charge: @robinhanhart  with help of @philippReist if needed
3. Making the setting persistent must be done via config file. I think doing this properly cross-platform might be too much work, especially with a planned installer for Win that will put the application in the program files folder where we need admin rights to write, but maybe there is a simple solution. What do you think @tiemes?
4. Store a swapped audio channels flag in the dancefile, so that swapped and regular files are loaded properly. In charge: @philippReist

**Comment by philippReist** [comment]
@robinhanhart: 2-4 are done in https://github.com/philippReist/DanceBotsEditor/tree/feature/audioswapflag

I added an ugly checkbox that should be working, so you can use this as a template to make it pretty (and move it to where it should be).

@tiemes: If you could UX test this on Mac / Win that would be great.

**Comment by robinhanhart** [comment]
@philippReist Thanks I'm on it 😄

**Comment by tiemes** [comment]
@philippReist works like it should on Win. Persistence works as well: after importing a swapped file, it gets automatically ticked. I dont have access to a Mac at the moment... @robinhanhart do you?

**Comment by robinhanhart** [comment]
@philippReist I just pushed a new commit with a new checkbox styling. Let me know what you think.

@tiemes Cannot compile on my mac, have cmake error. Windows works for me.

**Comment by tiemes** [comment]
@robinhanhart looks nice to me. I don't see why we should not stick with it.

**Comment by philippReist** [comment]
Thank you for testing and making it look nice!

What I am not sure about is if the checkmark should have such a prominent placement. My first instinct would have been to put it in a menu (i.e. a settings-gear next to the info) and hide it there as it is probably only rarely used.

But, if we load and set the swapped state from the mp3 file, it is not good if the result is hidden. So I think we can:
- Leave it as is
- Put into settings menu but trigger a popup if a file is loaded that is not consistent with the startup default (as determined by the config file)

What do you think?

**Comment by tiemes** [comment]
Exactly my thoughts. I first wanted it in a menu as well. But as we're likely using this feature a lot due to our swapped players, it might be a good idea to have it somewhere prominent. If our kids start, they have to enable swap and once they're done, they have to swap again to make sure they have a version which works at home as well. 
If they plug it directly into the laptop for testing purposes, they have to swap again. 
I can't think of any more option sliders we need so I think it's best to leave it, where it is now.

**Comment by philippReist** [comment]
Ok it definitely looks better now. But:
**Rename/add info:**
- I think it is not clear what this button does as "Swap Audio" (I know what I chose for the prototype) is not clear I think. Can you change it to a better name, @tiemes, and can we add a hover-tooltip that explains it a bit more?
- Can you please add some text to the readme as well, @tiemes?

**Make it less prominent**
Not sure if this makes sense but I would make the checkbox and text rather small to keep attention away and make it clear that this is not a key option to use. This is a mixed solution to the settings menu vs in the GUI approach.

**Comment by philippReist** [comment]
@robinhanhart the swap radio button does not seem to scale with the rest of the GUI, can you please have a look? You can work on the instaplay branch, it was rebased on the swap audio branch.

**Comment by robinhanhart** [comment]
@philippReist Scaling should now work correctly. I changed on the instaplay branch. See #70

**Comment by philippReist** [comment]
Thank you @robinhanhart!
