### ISSUE TITLE
Add Windows Installer

### ISSUE THREAD

**Issue by philippReist** [philippReist/DanceBotsEditor#72]
Provide installer that:
1. Extracts and copies files to Program Files or similar.
2. Creates Desktop/Start Menu shortcut to start GUI.

@philippReist to look into https://www.firegiant.com/wix/ to create MSI from zip file and create shortcuts.

**Comment by tiemes** [comment]
not sure if we should proceed with this. I think, we could stick with just providing the binaries as zip file.

**Comment by philippReist** [comment]
I can give it a try, but have not gotten around to it yet.

**Comment by tiemes** [comment]
up to you :)

**Comment by philippReist** [comment]
Made some good progress today on the installer: https://github.com/philippReist/DanceBotsEditor/tree/philippReist/wix

Need to finish the file parsing Python script to generate the wxs xml to be parsed by wix.

But this will create .MSI packages that allow:

- upgrading the DB editor from one version to the other by first deleting the existing installation
- Adding a shortcut to the start menu
- clean uninstall

Right now the installer has no UI, so it just installs into the program files. Can figure out how to add a destination path query, I think that should work. But let's get the installer working first.

**Comment by philippReist** [comment]
Ok I was too close to stop - now we have a first prototype. Let me know what you think @tiemes.

https://drive.google.com/file/d/11PxUl_B-Su40DrSngIdMd4QnRKgWzuuW/view?usp=sharing

**Comment by tiemes** [comment]
Awesome! :D Thanks a lot.
Installer works like a charm. I didn't test the software afterwards but installation was flaweless. 

1. Is there a way to evade rights elevation (admin)? I dont know if we could change the location and still add a startmenu shortcut.
2. Is there a way we could include our 30sec. mp3 folder with the installer? We're not allowed to store the mp3 files open on the repo. But if we could add them during the msi building, that would be nice. 

We could zoom or call to discuss if thats easier for you :)

**Comment by philippReist** [comment]
Hmm,

1. I am not sure if that is possible. I noticed that the installer writes to the registry for teh shortcut removal along with an uninstall from the win programs and features. Maybe the better approach is still the zip file, but structuring the folder to have a single folder with the executable and dlls in it and then a single shortcut to start the editor.
2. Yes we can include additional files - but I don't see the difference in being allowed to distribute samples with an installer that is available online vs. having them on the dancebots.ch page. Are you not free to use under 30s samples as you wish?

If a zoom call is easier we can set one up.

**Comment by tiemes** [comment]
sorry, been a bit busy...

1. I'm not sure. I quite like the installer though. It will make it easier for ISG ETH Services to manage our laptops as well, if we have an installer. I'll leave it up to you, but I prefer the intstaller.
2. I'd like to not have the mp3 files as mp3s in an open github repo. In the installer, I dont see any problem as we're allowed to ship them with the program. However if we had it on github, we'd make them publicly available without having to download the whole program and installing it.

**Comment by philippReist** [comment]
Also sorry for the late reply, had a busy time at work.

1. If the elevated privileges are ok, we can keep the installer then. You requested this, so you should make the call.
2. I will leave this completely up to you, as I think fair use copyright defenses are not straightforward. Just tell me what you need.

I think I can finish this next weekend, so we should finalize the plan.

**Comment by tiemes** [comment]
1. ok lets keep the elevated installer then.
2. lets integrate them into the final exe. What will be the path? Still C:/DanceBots? Or C:/program files/DanceBots? Do we just add an "mp3* folder to this?

**Comment by tiemes** [comment]
@philippReist: we should have an internal Version of the installer with the mp3 library and another without them. Do you have 1 mp3 file with an open licence we could include with the public version? It would be nice, if we could provide the software with 1 song to start.

**Comment by philippReist** [comment]
Sounds good. Configuring the installer is easy. Will do as soon as possible
so we are done with this version.
