### ISSUE TITLE
adapt mint & pepper styleguide to change color scheme for gui

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#73]
color scheme should be more compatible with m&p style guide.

**Comment by tiemes** [comment]
@robinhanhart what happened to this? Are we just gonna drop it? It certainly does look nice as it is.

**Comment by robinhanhart** [comment]
@tiemes I don't think it makes sense to adopt it. The Mint&Pepper style like the Flexo app gui would be not really possible as it is a light design and we use a lot more colors. Would just make the it harder to use if we reduce the colors.
