### ISSUE TITLE
DanceBots Editor wording

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#74]
In German, "DanceBots Editor" would require a hyphen: "DanceBots-Editor".
 If we treat it as English, "Editor" would not have a capital letter: "DanceBots editor"
Should we stick with "editor" or could we omit it at all and just use "DanceBots" in the titles? I don't think I would miss it. 
If we leave it, I'd suggest to change to lowercase as it is all in English. In German, we should use DanceBots-Editor with hyphen.

![image](https://user-images.githubusercontent.com/12649825/107238576-4bed2180-6a28-11eb-8483-10ed06927f4d.png)

**Comment by philippReist** [comment]
In English, I view DanceBots Editor as a title in which case Editor is capitalized.

I slightly lean toward leaving it as is in English, not changing it if German because I don't think we can localize the app name.

But if you see it as an issue we can also drop the editor.

**Comment by tiemes** [comment]
not entirely sure which way to go, but if we can't localize it, I'd probably drop it. 
I think "DanceBots" as brandname would be enough.
The issue came up with Startbahn29 which will start doing workshops as well. Our (and their) main audience is German speaking so we'd always have to reference it in German anyway. If we drop it here, we'd only have one version. Otherwise it would be with hyphen in German and without in the Software.

**Comment by philippReist** [comment]
Ok sounds good let's drop editor.

**Comment by philippReist** [comment]
If it's ok with you @tiemes, I would like to leave the naming as it is, as we would have to change all the build / deploy chain names as well, and the continuous integration would be affected as well.

I'd rather spend that time on the installer.
