### ISSUE TITLE
titel autor doesnt support mutated vowels (e.g. ä, ö)

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#76]
[](url)
before saving
![beforesaving](https://user-images.githubusercontent.com/12649825/112855839-80d43700-90af-11eb-8080-096d86680315.PNG)
after saving/on next open
![afterloading](https://user-images.githubusercontent.com/12649825/112855836-803ba080-90af-11eb-99b6-df4c228a4ffe.PNG)

The gui/software doesnt seem to accept "umlaute". Didn't check any other non-ascii characters. One can write them into the fields, once the file is exported/saved, the chars get destroyed.

**Comment by philippReist** [comment]
Oh interesting. I will have a look!

**Comment by tiemes** [comment]
could you have a look into it yet?

**Comment by philippReist** [comment]
Not yet but will do. I think we have a plan now how to finish the next release.
