### ISSUE TITLE
sound on both lines

### ISSUE THREAD

**Issue by tiemes** [philippReist/DanceBotsEditor#81]
Von der Startbahn29:
Wenn ich das programmierte File auf den MP3 Player lade, und den Dancebot anstecke kommt die Musik nur sehr schlecht und die Motorenbewegungen und die LED's stimmen nicht überein mit dem Programmierten. Der Dancebot macht eher komische, willkürliche Zitterbewegungen und die LED's leuchten irgendwie, nur nicht so wie programmiert. 
Wenn ich das File mit einem Kopfhörer anhöre, kommt nicht, wie eigentlich erwartet, auf dem einen Kanal die Musik, und auf dem anderen dieses Störgeräusch (Motoren und LED-Befehle), sondern auf dem einen Kanal das Störgeräusch gemischt mit der Musik und auf dem anderen Kanal nur das Störgeräusch. 
 
Hattet ihr das auch schonmal? Und habt ihr eine Lösung für das Problem?

nachtrag: Ich habs jetzt nochmals probiert mit einem neuen Lied und der neuen Software und es funktioniert leider trotzdem nicht. 
Irgendwie sind die Befehle und die Musik nicht klar getrennt auf die zwei Kanäle...
@philippReist

**Comment by philippReist** [comment]
A few ideas:
1. Test the file with another MP3 Player or Laptop.
2. Test playback at different volume levels of the MP3 Player
3. Unlikely, but mixing of data and music can occur if an old Dancebots file is loaded into the program.

**Comment by Pascale-lab** [comment]
Dear Philipp Reist

Thank you for your ideas.

I tried all of your steps, but unfortunately nothing helped. 

I think its not the Problem, that the software mixes the data. Its more a problem of the MP3-Player. It seems, that the MP3-Player does not split the to channels correctly when coupled to the Dancebot. When i listen to the programmed file with earphones, i hear on one channel the sound of the orders (motor & LED) and on the other one i hear a mix of ordersound and music....

**Comment by r-oung** [comment]
I actually had the same mixing problem.

I verified that there is no mixing in the data by opening it up in Audacity:
![Screenshot from 2021-10-01 13-31-07](https://user-images.githubusercontent.com/44389573/135569380-57596d93-5e49-47f9-9b6d-47a7d88e17a9.png)

The problem for me was that I was running the audio through one of these [cheap 3.5mm extension cables](https://www.amazon.com/AmazonBasics-3-5mm-Female-Stereo-Audio/dp/B01CNAUYBY/ref=sr_1_4?dchild=1&keywords=mini+jack+extension+amazon+basic&qid=1633065810&sr=8-4). When I removed the extension cable, there was no mixing. I suspect there's little to no EMI shielding between the L/R audio lines in the extension cable.

The MP3 player that you are using probably has the same issue with EMI shielding. Unfortunately, there's little that can be done unless you want to modify the hardware..
