### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by r-oung** [philippReist/DanceBotsEditor#85]
@philippReist I don't know about you, but the video on the [Home page](http://www.dancebots.ch) shows as "Unavailable". Also, it's still using HTTP instead of HTTPS. Not that it really matters here, but in the future some browsers might not display HTTP.

![Screen Shot 2021-10-01 at 17 55 33](https://user-images.githubusercontent.com/44389573/135593334-3b76111a-59f9-4f62-8726-7e70441d1cfd.png)

I don't know what you're hosting this on, but I could put something together and host it on GitHub pages instead. Hosting is free and content can be modified directly in GitHub. Thoughts?

**Comment by philippReist** [comment]
I could fix the broken videos on the video page but cannot update the main page. @tiemes could you please have a look?

I get:
`Updating failed. The response is not a valid JSON response.`

**Comment by tiemes** [comment]
@r-oung @philippReist I get the same response. 
I'd suggest someone updates the php and other dependencies.

**Comment by r-oung** [comment]
@philippReist @tiemes Is this the original page? Do I still have admin access?

**Comment by tiemes** [comment]
@philippReist @r-oung according to Stefan Bertschi, at least one of you should have admin rights.

**Comment by philippReist** [comment]
Yes I have admin access but I think this needs access to the server where this is running. Can you or Stefan please look into this issue, @tiemes?

**Comment by philippReist** [comment]
I haven't seen the new trailer - its great! And yes I would put that on the landing page.

**Comment by tiemes** [comment]
I don't have any rights. When I asked Stefan last week, he told me, you should have sufficient rights. 
There's not much I can do. If you could email him directly with a specific request we'd probably have the best chances ;-)

**Comment by tiemes** [comment]
I hadn't know about the trailer until last week as well :D
I'll check with Hanna. Whats your and r-oungs correct spelling? 

btw, I'm leaving mint & pepper to focus on the Cybathlon @school project. As I only have 20% a week, I cannot do justice to all project mint & pepper has. Hanna would be the new project leader and Philipp Egger Engineer.

**Comment by philippReist** [comment]
Thanks - Raymond Oung and Philipp Reist, please.

Sad to see you go and thanks for all your help!

**Comment by r-oung** [comment]
> Sad to see you go and thanks for all your help!
@tiemes All the best to you!

**Comment by philippReist** [comment]
For some weird reason, I could fix the website after changing 10 and 18 to ten and eighteen in the text body.

The downloads are updated, too.
